services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./custom-modules:/mnt/custom-modules
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-filestore:/var/lib/odoo
    command: ["python3", "odoo-bin", "-c", "/etc/odoo/odoo.conf"]

volumes:
  odoo-db-data:
  odoo-filestore:
