services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom-modules:/mnt/custom-modules
      - odoo-filestore:/root/.local/share/Odoo
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command: ["--dev=xml,reload,qweb", "--addons-path=/odoo/addons,/mnt/custom-modules"]

volumes:
  odoo-db-data:
  odoo-filestore:
