[options]
addons_path = /odoo/addons,/mnt/custom-modules
data_dir = /var/lib/odoo
admin_passwd = admin_dev_only
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
xmlrpc_port = 8069
logfile = False
log_level = info

; dev flags: recarga automática de XML/QWeb sin reiniciar
dev_mode = xml,reload,qweb
